default_agent: ecocoderagentcore
agents:
  ecocoderagentcore:
    name: ecocoderagentcore
    entrypoint: /Users/ali/Source/EcoCoderAgentCore/app/agent.py
    platform: linux/arm64
    container_runtime: none
    source_path: /Users/ali/Source/EcoCoderAgentCore/app
    aws:
      execution_role: arn:aws:iam::434114167546:role/AmazonBedrockAgentCoreSDKRuntime-ap-southeast-1-b953f47315
      execution_role_auto_create: false
      account: '434114167546'
      region: ap-southeast-1
      ecr_repository: 434114167546.dkr.ecr.ap-southeast-1.amazonaws.com/bedrock-agentcore-ecocoderagentcore
      ecr_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
    bedrock_agentcore:
      agent_id: ecocoderagentcore-H0kpdY5A85
      agent_arn: arn:aws:bedrock-agentcore:ap-southeast-1:434114167546:runtime/ecocoderagentcore-H0kpdY5A85
      agent_session_id: ee541b82-7438-49ca-b633-565cb63bfbcd
    codebuild:
      project_name: bedrock-agentcore-ecocoderagentcore-builder
      execution_role: arn:aws:iam::434114167546:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-southeast-1-b953f47315
      source_bucket: bedrock-agentcore-codebuild-sources-434114167546-ap-southeast-1
    memory:
      mode: STM_ONLY
      memory_id: ecocoderagentcore_mem-eVk8F8D2Mc
      memory_arn: arn:aws:bedrock-agentcore:ap-southeast-1:434114167546:memory/ecocoderagentcore_mem-eVk8F8D2Mc
      memory_name: ecocoderagentcore_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
